import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getBootstrappedFlags } from "./client";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const publishableKey = process.env.REFLAG_PUBLISHABLE_KEY || "";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // In a real app, you'd get user/company from your auth system
  const flags = await getBootstrappedFlags({
    user: {
      id: "demo-user",
      email: "demo-user@example.com",
      "optin-huddles": true,
    },
    company: { id: "demo-company", name: "Demo Company" },
    other: { source: "web" },
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers publishableKey={publishableKey} flags={flags}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
